name: "Check spelling"
on:
  pull_request:
  push:

jobs:
  spellcheck:
    name: "Check spelling"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
